services:
  go_backend:
    container_name: go_backend
    image: go_backend:1.0.0
    build: 
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://root:root@db:5432/root?sslmode=disabled'
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    container_name: db 
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
